version: '3.5'

services:
  urap-db:
    container_name: urap-db
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=${URAP_BACKEND_USER}:${URAP_BACKEND_PASSWORD}
    networks:
      - default
  urap-backend:
    container_name: urap-backend
    image: urap:latest
    ports:
      - "8080:8080"
    environment:
      - db_host=urap-db
    networks:
      - default
    depends_on:
      - urap-db

networks:
  default:
    driver: bridge
    name: urap-network

volumes:
  db-data:
    name: db-data